-- =======================================================
-- CORRECCAO DE SEGURANCA: newsletter_subscribers
-- Executar no Supabase > SQL Editor
-- =======================================================

-- 1. Criar a tabela caso não exista
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Activar RLS (corrige o alerta do Security Advisor)
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- 3. Policy: qualquer visitante pode SUBSCREVER (INSERT)
--    (necessário para o formulário do Footer funcionar)
CREATE POLICY "Inserção pública permitida"
    ON newsletter_subscribers
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- 4. SEM policy de SELECT, UPDATE ou DELETE para anon
--    (os subscritores só são visíveis para o admin autenticado)

-- =======================================================
-- NOTA: Executar este SQL no painel do Supabase:
-- Dashboard > SQL Editor > New query > Colar e executar
-- Após execução, o erro no Security Advisor desaparece.
-- =======================================================
