-- Tabela para Gestão de Tipos de Produtos e Taxas de IVA no Supabase
CREATE TABLE IF NOT EXISTS tax_rates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    type text unique not null,
    rate numeric not null,
    description text
);

-- Inserção das taxas padrão em Portugal
INSERT INTO tax_rates (type, rate, description) VALUES
    ('Tinto', 13, 'Vinho Tinto (Taxa Intermédia)'),
    ('Branco', 13, 'Vinho Branco (Taxa Intermédia)'),
    ('Rosé', 13, 'Vinho Rosé (Taxa Intermédia)'),
    ('Espumante', 13, 'Espumante (Taxa Intermédia)'),
    ('Cave', 13, 'Vinhos de Cave / Coleção (Taxa Intermédia)'),
    ('Azeite', 6, 'Azeite Virgem e Alimentar (Taxa Reduzida)'),
    ('Licores / Destilados', 23, 'Bebidas Espirituosas e Licores (Taxa Normal)'),
    ('Outros', 23, 'Cabazes, Acessórios e Outros (Taxa Normal)')
ON CONFLICT (type) DO UPDATE SET rate = EXCLUDED.rate;

-- Políticas de RLS
ALTER TABLE tax_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Tax Rates" ON tax_rates FOR SELECT USING (true);
CREATE POLICY "Public Write Tax Rates" ON tax_rates FOR ALL USING (true);
